"""Golden tests for the computation engine.

Every expected figure here was worked out by hand from the statute, not
generated by running the code. That is the only kind of test worth having for a
tax engine — a test that records what the code currently does merely freezes
its bugs in place.
"""

from __future__ import annotations

from datetime import date

import pytest

from app.money import D
from app.schemas import (
    CapitalGainItem,
    HouseProperty,
    SalaryIncome,
    TaxPayment,
    TaxReturn,
)
from app.tax.engine import compare_regimes, compute, tax_on_slabs
from app.tax.rules import get_ay

# A filing date on or before the due date, so interest never muddies a slab test.
ON_TIME = date(2026, 7, 25)


def make_return(salary: int = 0, **kwargs) -> TaxReturn:
    tr = TaxReturn(assessment_year="2026-27", filing_date=ON_TIME, **kwargs)
    if salary:
        tr.salaries = [
            SalaryIncome(employer_name="Employer", employer_tan="ABCD12345E",
                         salary_17_1=D(salary))
        ]
    return tr


# --------------------------------------------------------------------------
# New regime slabs — Finance Act 2025
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "gross, expected_total_income, expected_tax_before_rebate",
    [
        # 4L nil band starts after the 75k standard deduction.
        (475_000, 400_000, 0),
        # 8L: 5% on the 4L-8L band = 20,000.
        (875_000, 800_000, 20_000),
        # 12L: 20,000 + 10% of 4L = 60,000. Fully wiped by the rebate.
        (1_275_000, 1_200_000, 60_000),
        # 16L: + 15% of 4L = 1,20,000.
        (1_675_000, 1_600_000, 120_000),
        # 20L: + 20% of 4L = 2,00,000.
        (2_075_000, 2_000_000, 200_000),
        # 24L: + 25% of 4L = 3,00,000.
        (2_475_000, 2_400_000, 300_000),
        # 30L: 3,00,000 + 30% of 6L = 4,80,000.
        (3_075_000, 3_000_000, 480_000),
    ],
)
def test_new_regime_slab_boundaries(gross, expected_total_income,
                                    expected_tax_before_rebate):
    comp = compute(make_return(gross), "new")
    assert comp.total_income == D(expected_total_income)
    assert comp.tax_on_normal_income == D(expected_tax_before_rebate)


def test_standard_deduction_is_75000_in_new_regime():
    comp = compute(make_return(1_000_000), "new")
    assert comp.salary == D(925_000)


def test_standard_deduction_is_50000_in_old_regime():
    comp = compute(make_return(1_000_000), "old")
    assert comp.salary == D(950_000)


# --------------------------------------------------------------------------
# Section 87A
# --------------------------------------------------------------------------


def test_87a_makes_1275000_salary_tax_free():
    """The headline promise of the Finance Act 2025."""
    comp = compute(make_return(1_275_000), "new")
    assert comp.total_income == D(1_200_000)
    assert comp.rebate_87a == D(60_000)
    assert comp.total_tax_liability == D(0)


def test_87a_marginal_relief_just_above_the_ceiling():
    """At ₹12,10,000 of total income the tax may not exceed the ₹10,000 excess."""
    tr = make_return(1_285_000)          # 12,85,000 - 75,000 = 12,10,000
    comp = compute(tr, "new")
    assert comp.total_income == D(1_210_000)
    # Slab tax would be 61,500; relief caps the payable at the 10,000 excess.
    assert comp.tax_on_normal_income == D(61_500)
    assert comp.tax_after_rebate == D(10_000)


def test_87a_denied_against_capital_gains_in_new_regime():
    """Section 115BAC(1A) allows the rebate only against slab-rate income."""
    tr = make_return(400_000)
    tr.capital_gains = [
        CapitalGainItem(category="stcg_111a", description="Equity",
                        sale_consideration=D(500_000),
                        cost_of_acquisition=D(200_000))
    ]
    comp = compute(tr, "new")
    # Normal income is 3,25,000 — below the 4L exemption, so no slab tax. The
    # unused 75,000 shelters part of the gain; the rest is taxed at 20% with no
    # rebate available against it.
    assert comp.tax_on_normal_income == D(0)
    assert comp.rebate_87a == D(0)
    assert comp.tax_on_special_income > 0


def test_old_regime_87a_ceiling_is_500000():
    comp = compute(make_return(550_000), "old")
    assert comp.total_income == D(500_000)
    assert comp.rebate_87a == D(12_500)
    assert comp.total_tax_liability == D(0)


# --------------------------------------------------------------------------
# Capital gains
# --------------------------------------------------------------------------


def test_112a_exemption_is_a_rate_threshold_not_a_deduction():
    """The ₹1.25 lakh does not leave total income — section 112A(2)."""
    tr = make_return(1_000_000)
    tr.capital_gains = [
        CapitalGainItem(category="ltcg_112a", description="INFY",
                        sale_consideration=D(825_000),
                        cost_of_acquisition=D(500_000))
    ]
    comp = compute(tr, "new")
    # Total income carries the whole 3,25,000 gain.
    assert comp.gross_total_income == D(1_250_000)
    slice_ = next(s for s in comp.special_slices if s.code == "ltcg_112a")
    assert slice_.income == D(325_000)
    assert slice_.statutory_exemption == D(125_000)
    assert slice_.chargeable == D(200_000)
    assert slice_.tax == D(25_000)          # 12.5% of 2,00,000


def test_stcg_111a_is_20_percent():
    tr = make_return(1_000_000)
    tr.capital_gains = [
        CapitalGainItem(category="stcg_111a", sale_consideration=D(300_000),
                        cost_of_acquisition=D(200_000))
    ]
    comp = compute(tr, "new")
    slice_ = next(s for s in comp.special_slices if s.code == "stcg_111a")
    assert slice_.tax == D(20_000)


def test_unused_basic_exemption_shelters_capital_gains_for_a_resident():
    """Provisos to sections 111A(1), 112(1)(a) and 112A(2)."""
    tr = make_return(0)
    tr.capital_gains = [
        CapitalGainItem(category="ltcg_112a", sale_consideration=D(700_000),
                        cost_of_acquisition=D(200_000))
    ]
    comp = compute(tr, "new")
    slice_ = comp.special_slices[0]
    assert slice_.income == D(500_000)
    assert slice_.statutory_exemption == D(125_000)
    # 4,00,000 of unused basic exemption absorbs the rest.
    assert slice_.basic_exemption_used == D(375_000)
    assert comp.total_tax_liability == D(0)


def test_non_resident_gets_no_basic_exemption_against_gains():
    tr = make_return(0)
    tr.taxpayer.residential_status = "NRI"
    tr.capital_gains = [
        CapitalGainItem(category="ltcg_112a", sale_consideration=D(700_000),
                        cost_of_acquisition=D(200_000))
    ]
    comp = compute(tr, "new")
    assert comp.special_slices[0].basic_exemption_used == D(0)


def test_112a_grandfathering_uses_fmv_on_31_jan_2018():
    tr = make_return(0)
    tr.capital_gains = [
        CapitalGainItem(
            category="ltcg_112a", sale_consideration=D(1_000_000),
            cost_of_acquisition=D(200_000), fmv_31jan2018=D(700_000),
        )
    ]
    comp = compute(tr, "new")
    # Cost becomes the higher of 2,00,000 and min(7,00,000, 10,00,000).
    assert comp.capital_gains == D(300_000)


def test_short_term_loss_sets_off_against_the_highest_taxed_gain():
    """Section 70 lets a short-term loss go against any capital gain."""
    tr = make_return(1_500_000)
    tr.capital_gains = [
        # 20% bucket
        CapitalGainItem(category="stcg_111a", sale_consideration=D(400_000),
                        cost_of_acquisition=D(200_000)),
        # 12.5% bucket
        CapitalGainItem(category="ltcg_112a", sale_consideration=D(600_000),
                        cost_of_acquisition=D(200_000)),
        # a short-term loss of 1,50,000
        CapitalGainItem(category="stcg_slab", sale_consideration=D(50_000),
                        cost_of_acquisition=D(200_000)),
    ]
    comp = compute(tr, "new")
    stcg = next(s for s in comp.special_slices if s.code == "stcg_111a")
    # The loss lands on the 20% bucket first: 2,00,000 - 1,50,000 = 50,000.
    assert stcg.income == D(50_000)


def test_long_term_loss_cannot_touch_a_short_term_gain():
    tr = make_return(1_500_000)
    tr.capital_gains = [
        CapitalGainItem(category="stcg_111a", sale_consideration=D(400_000),
                        cost_of_acquisition=D(200_000)),
        CapitalGainItem(category="ltcg_112_other", sale_consideration=D(50_000),
                        cost_of_acquisition=D(250_000)),
    ]
    comp = compute(tr, "new")
    stcg = next(s for s in comp.special_slices if s.code == "stcg_111a")
    assert stcg.income == D(200_000)        # untouched by the long-term loss
    assert comp.carried_forward.get("ltcl") == D(200_000)


def test_property_takes_the_cheaper_of_flat_and_indexed():
    """Fifth proviso to section 112(1), for a pre-23-July-2024 acquisition."""
    tr = make_return(1_500_000)
    tr.capital_gains = [
        CapitalGainItem(
            category="ltcg_112_property", description="Flat",
            purchase_date=date(2012, 6, 1), sale_date=date(2025, 8, 1),
            sale_consideration=D(10_000_000), cost_of_acquisition=D(3_000_000),
            indexed_cost_of_acquisition=D(6_000_000),
        )
    ]
    comp = compute(tr, "new")
    # Flat: 12.5% of 70,00,000 = 8,75,000. Indexed: 20% of 40,00,000 = 8,00,000.
    slice_ = next(s for s in comp.special_slices
                  if s.code == "ltcg_112_property_indexed")
    assert slice_.income == D(4_000_000)
    assert slice_.tax == D(800_000)


# --------------------------------------------------------------------------
# House property
# --------------------------------------------------------------------------


def test_self_occupied_interest_capped_at_2_lakh_in_old_regime():
    tr = make_return(1_500_000)
    tr.house_properties = [
        HouseProperty(property_type="SOP", interest_24b=D(300_000))
    ]
    comp = compute(tr, "old")
    assert comp.house_property == D(-200_000)


def test_self_occupied_interest_is_nil_in_new_regime():
    tr = make_return(1_500_000)
    tr.house_properties = [
        HouseProperty(property_type="SOP", interest_24b=D(300_000))
    ]
    comp = compute(tr, "new")
    assert comp.house_property == D(0)


def test_let_out_loss_setoff_capped_at_2_lakh_with_carry_forward():
    """Section 71(3A) caps the inter-head set-off; section 71B carries the rest."""
    tr = make_return(2_000_000)
    tr.house_properties = [
        HouseProperty(property_type="LOP", annual_rent_received=D(240_000),
                      municipal_taxes_paid=D(0), interest_24b=D(800_000))
    ]
    comp = compute(tr, "old")
    # NAV 2,40,000 less 30% = 1,68,000, less interest 8,00,000 = -6,32,000.
    assert comp.house_property == D(-200_000)
    assert comp.carried_forward["house_property"] == D(432_000)


def test_let_out_standard_deduction_is_30_percent_of_net_annual_value():
    tr = make_return(0)
    tr.house_properties = [
        HouseProperty(property_type="LOP", annual_rent_received=D(600_000),
                      municipal_taxes_paid=D(50_000))
    ]
    comp = compute(tr, "old")
    # (6,00,000 - 50,000) × 70% = 3,85,000.
    assert comp.house_property == D(385_000)


# --------------------------------------------------------------------------
# Chapter VI-A
# --------------------------------------------------------------------------


def test_80c_ceiling_is_shared_across_80c_80ccc_and_80ccd1():
    tr = make_return(1_500_000)
    tr.deductions.s80c = D(150_000)
    tr.deductions.s80ccd1 = D(50_000)
    comp = compute(tr, "old")
    assert comp.deductions_total == D(150_000)


def test_80ccd1b_is_on_top_of_the_80c_ceiling():
    tr = make_return(1_500_000)
    tr.deductions.s80c = D(150_000)
    tr.deductions.s80ccd1b = D(50_000)
    comp = compute(tr, "old")
    assert comp.deductions_total == D(200_000)


def test_new_regime_allows_only_employer_nps():
    tr = make_return(1_500_000)
    tr.deductions.s80c = D(150_000)
    tr.deductions.s80d_self = D(25_000)
    tr.deductions.s80ccd2 = D(100_000)
    comp = compute(tr, "new")
    assert comp.deductions_total == D(100_000)
    sections = {line.section for line in comp.deduction_detail.disallowed}
    assert "80C" in sections and "80D" in sections


def test_employer_nps_capped_at_14_percent_in_new_regime():
    tr = make_return(1_000_000)
    tr.deductions.s80ccd2 = D(200_000)
    comp = compute(tr, "new")
    assert comp.deductions_total == D(140_000)


def test_employer_nps_capped_at_10_percent_in_old_regime():
    tr = make_return(1_000_000)
    tr.deductions.s80ccd2 = D(200_000)
    comp = compute(tr, "old")
    assert comp.deductions_total == D(100_000)


def test_80d_senior_citizen_limit():
    tr = make_return(1_500_000)
    tr.taxpayer.date_of_birth = date(1960, 1, 1)   # 66 in FY 2025-26
    tr.deductions.s80d_self = D(60_000)
    comp = compute(tr, "old")
    line = next(l for l in comp.deduction_detail.lines if l.section == "80D")
    assert line.allowed == D(50_000)


def test_80ttb_replaces_80tta_for_a_senior_citizen():
    tr = make_return(600_000)
    tr.taxpayer.date_of_birth = date(1958, 3, 1)
    tr.other_sources.fixed_deposit_interest = D(80_000)
    comp = compute(tr, "old")
    sections = {line.section for line in comp.deduction_detail.lines}
    assert "80TTB" in sections and "80TTA" not in sections
    line = next(l for l in comp.deduction_detail.lines if l.section == "80TTB")
    assert line.allowed == D(50_000)


def test_chapter_via_cannot_be_set_against_special_rate_income():
    """Sections 111A(2), 112(2) and 112A(6)."""
    tr = make_return(0)
    tr.capital_gains = [
        CapitalGainItem(category="stcg_111a", sale_consideration=D(1_000_000),
                        cost_of_acquisition=D(0))
    ]
    tr.deductions.s80c = D(150_000)
    comp = compute(tr, "old")
    assert comp.deductions_total == D(0)


# --------------------------------------------------------------------------
# Surcharge
# --------------------------------------------------------------------------


def test_surcharge_starts_above_50_lakh():
    comp = compute(make_return(6_000_000), "new")
    assert comp.total_income == D(5_925_000)
    assert comp.tax_on_normal_income == D(1_357_500)
    assert comp.surcharge == D(135_750)          # 10%
    assert comp.cess == D(59_730)


def test_surcharge_marginal_relief_just_above_50_lakh():
    """Tax plus surcharge may not exceed the tax at ₹50 lakh plus the excess."""
    comp = compute(make_return(5_085_000), "new")
    assert comp.total_income == D(5_010_000)
    assert comp.tax_on_normal_income == D(1_083_000)
    # Tax at exactly 50 lakh is 10,80,000; the ceiling is 10,90,000.
    assert comp.surcharge == D(7_000)
    assert comp.surcharge_marginal_relief == D(101_300)


def test_new_regime_surcharge_tops_out_at_25_percent():
    comp = compute(make_return(80_000_000), "new")
    top = max(band.rate for band in get_ay("2026-27").regimes["new"].surcharge_bands)
    assert top == D("0.25")
    assert comp.surcharge > 0


def test_old_regime_keeps_the_37_percent_band():
    top = max(band.rate for band in get_ay("2026-27").regimes["old"].surcharge_bands)
    assert top == D("0.37")


def test_surcharge_on_capital_gains_capped_at_15_percent():
    tr = make_return(3_000_000)
    tr.capital_gains = [
        CapitalGainItem(category="ltcg_112a", sale_consideration=D(30_000_000),
                        cost_of_acquisition=D(0))
    ]
    comp = compute(tr, "old")
    # Total income is above ₹2 crore, so normal income attracts 25% but the
    # capital-gains slice is held to 15%.
    cg_tax = comp.tax_on_special_income
    normal_tax = comp.tax_after_rebate - cg_tax
    expected = normal_tax * D("0.25") + cg_tax * D("0.15")
    assert comp.surcharge == pytest.approx(float(expected), rel=1e-9)


# --------------------------------------------------------------------------
# Interest and fees
# --------------------------------------------------------------------------


def test_no_interest_when_filed_on_time_with_full_tds():
    tr = make_return(1_500_000)
    tr.taxes_paid.payments = [
        TaxPayment(kind="tds_salary", deductor_tan="ABCD12345E",
                   amount=D(200_000))
    ]
    comp = compute(tr, "new")
    assert comp.interest.total == D(0)


def test_234f_fee_for_a_belated_return():
    tr = make_return(1_500_000)
    tr.filing_date = date(2026, 9, 10)
    comp = compute(tr, "new")
    assert comp.interest.section_234f == D(5_000)


def test_234f_is_1000_when_total_income_is_under_5_lakh():
    tr = make_return(560_000)
    tr.filing_date = date(2026, 9, 10)
    comp = compute(tr, "new")
    assert comp.total_income == D(485_000)
    assert comp.interest.section_234f == D(1_000)


def test_234b_not_charged_when_90_percent_was_paid_in_advance():
    tr = make_return(2_000_000)
    tr.filing_date = date(2026, 9, 10)
    comp_without = compute(tr, "new")
    tr.taxes_paid.payments = [
        TaxPayment(kind="tds_salary", deductor_tan="ABCD12345E",
                   amount=comp_without.total_tax_liability)
    ]
    comp = compute(tr, "new")
    assert comp.interest.section_234b == D(0)


def test_senior_citizen_without_business_income_escapes_advance_tax():
    tr = make_return(1_500_000)
    tr.taxpayer.date_of_birth = date(1955, 1, 1)
    tr.filing_date = date(2026, 9, 10)
    tr.has_business_income = False
    comp = compute(tr, "new")
    assert comp.interest.section_234b == D(0)
    assert comp.interest.section_234c == D(0)


# --------------------------------------------------------------------------
# Regime comparison and rounding
# --------------------------------------------------------------------------


def test_comparison_prefers_the_cheaper_regime():
    tr = make_return(1_500_000)
    tr.deductions.s80c = D(150_000)
    tr.deductions.s80ccd1b = D(50_000)
    tr.deductions.s80d_self = D(25_000)
    comparison = compare_regimes(tr)
    assert comparison.recommended in ("new", "old")
    cheaper = min(comparison.new.total_tax_liability,
                  comparison.old.total_tax_liability)
    assert comparison.chosen.total_tax_liability == cheaper


def test_explicit_regime_choice_overrides_the_recommendation():
    tr = make_return(1_500_000, regime_choice="old")
    assert compare_regimes(tr).recommended == "old"


def test_net_payable_is_rounded_to_the_nearest_ten():
    """Section 288B."""
    tr = make_return(1_234_567)
    comp = compute(tr, "new")
    assert comp.net_payable % D(10) == 0


def test_slab_helper_is_progressive_not_flat():
    bands = get_ay("2026-27").regimes["new"].slabs_by_age["below_60"]
    assert tax_on_slabs(D(400_000), bands) == D(0)
    assert tax_on_slabs(D(800_000), bands) == D(20_000)
    assert tax_on_slabs(D(0), bands) == D(0)
